### ISSUE TITLE
Collaborators' Review

### ISSUE THREAD

**Issue by ugoiloh** [HamoyeHQ/01-University-Admissions#5]
Hey guys,

I observe that pull requests are merged to master branch without reviews and comments from team members. This is not a good practice for open source. 

I just spotted from the EDA that the visuals are not titled as well as did not follow some data visualization rules. In fact, the collaboration behind open source is embedded in this comment and review practice. 

@PL, please, this is necessary going forward.

🥺 🥺

**Comment by Sillians** [comment]
> Hey guys,
> 
> I observe that pull requests are merged to master branch without reviews and comments from team members. This is not a good practice for open source.
> 
> I just spotted from the EDA that the visuals are not titled as well as did not follow some data visualization rules. In fact, the collaboration behind open source is embedded in this comment and review practice.
> 
> @pl, please, this is necessary going forward.
> 
> 🥺 🥺

thanks @ugoiloh , I just observed that now.., Please Guys it is not a good practice to merge your pull requests with the Master branch. it literally doesn't make much sense for an Open source project.

**Comment by gauravjain2** [comment]
Every Team Member, do take care of this issue.
Create a Pull Request instead of directly merging the code changes.
